version: '3.8'

services:
  webberry-postgres:
    container_name: webberry-postgres
    hostname: webberry-postgres
    image: postgres:13.0-alpine
    env_file:
      - ./app/.env
    networks:
      - webberry-main-net
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
    command: -p 5432

  webberry-app:
    container_name: webberry-app
    hostname: webberry-app
    build: 
      context: ./app
      args:
        REPO_PATH: ./
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    environment:
      - "MIGRATIONS=1"
    volumes:
      - ./app:/app
    ports:
      - "0.0.0.0:8006:8006"
    restart: always
    depends_on:
      - webberry-postgres
    working_dir: /app
    networks:
      - webberry-main-net


volumes:
  postgresql-data:
    driver: local

networks:
  webberry-main-net:
    driver: bridge
